" NERDTreeToggle() by pressing <C-k>
map <C-k> :NERDTreeToggle<CR>

" solarized-dark theme
let g:solarized_termtrans = 1
syntax enable
set background=dark
colorscheme solarized

" increase vimupdate time (default is 4000)
" useful for vim-gitgutter
set updatetime=100

" recommended syntastic settings
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
